name: build

on:
  push:
    branches:
    - main
    paths:
    - '.github/**'
    - 'src/**'
    - '*.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
     
    - name: Install npm
      run: npm install roblox-ts --no-save --no-package-lock

    - name: Build
      run: npm run prepublishOnly

    - name: Publish
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        DEPLOY_DIR: out
        SRC_PACKAGE_DIR: src


